<?php

$labels['buttontitle'] = 'Löschen alte Nachrichten';
$labels['buttontext'] = 'Säubern';
$labels['numdeleted'] = ' Nachrichten wurden erfolgreich gelöscht.';
$labels['numchecked'] = ' Nachrichten könnten gelöscht werden.';

$labels['deloldmsgs'] = 'Alte Nachrichten löschen';
$labels['deleteold'] = 'Nachrichten löschen nach';
$labels['whenauto'] = 'Automatisches Löschen';
$labels['check'] = 'Prüfen';
$labels['delete'] = 'Löschen';
$labels['autonever'] = 'Niemals';
$labels['autologin'] = 'Bei der Anmeldung';
$labels['autologout'] = 'Beim Abmelden';
$labels['default'] = 'Standard';
$labels['never'] = '- Niemals -';
$labels['1_week'] = '1 Woche';
$labels['2_week'] = '2 Wochen';
$labels['1_month'] = '1 Monat';
$labels['2_month'] = '2 Monate';
$labels['6_month'] = '6 Monate';
$labels['1_year'] = '1 Jahr';
$labels['2_year'] = '2 Jahre';
$labels['3_year'] = '3 Jahre';
$labels['4_year'] = '4 Jahre';

$messages['checking'] = 'Prüfen auf alte Nachrichten ...';
$messages['deleting'] = 'Alte Nachrichten werden gelöscht ...';
$messages['dlgtxt'] = '<div id="dstus">Löschen (oder prüfen auf) alte Nachrichten.</div>';

$messages['deloldcfrm'] = 'Dadurch werden alte E-Mails gemäß den Einstellungen dauerhaft aus allen Ordnern entfernt. Möchten Sie fortfahren?';
$messages['blurbcontent'] = 'Sie können einen globalen Wert festlegen, der für alle Ordner gilt, für die keine eigene Einstellung festgelegt wurde (Standardeinstellung). '.
			'Informationen zum Festlegen von Werten für bestimmte Ordner finden Sie unter <i>Ordnereinstellungen</i>.<br><br>Das Löschen alter Nachrichten kann automatisch beim Anmelden '.
			'oder Abmelden erfolgen. Das Löschen zu anderen Zeiten kann über das Symbol in der Mail-Menüleiste erfolgen.';
