<?php

$labels['buttontitle'] = 'Delete old messages';
$labels['buttontext'] = 'Clean';
$labels['numdeleted'] = ' messages were sucessfully deleted.';
$labels['numchecked'] = ' messages could be deleted.';

$labels['deloldmsgs'] = 'Delete Old Messages';
$labels['deleteold'] = 'Delete messages after';
$labels['whenauto'] = 'Automatic deletion';
$labels['check'] = 'Check';
$labels['delete'] = 'Delete';
$labels['autonever'] = 'Never';
$labels['autologin'] = 'At Login';
$labels['autologout'] = 'At Logout';
$labels['default'] = 'default';
$labels['never'] = '- never -';
$labels['1_week'] = '1 Week';
$labels['2_week'] = '2 Weeks';
$labels['1_month'] = '1 Month';
$labels['2_month'] = '2 Months';
$labels['6_month'] = '6 Months';
$labels['1_year'] = '1 Year';
$labels['2_year'] = '2 Years';
$labels['3_year'] = '3 Years';
$labels['4_year'] = '4 Years';
$labels['5_year'] = '5 Years';
$labels['10_year'] = '10 Years';
$labels['15_year'] = '15 Years';

$messages['checking'] = 'Checking for old messages...';
$messages['deleting'] = 'Deleting old messages...';
$messages['dlgtxt'] = '<div id="dstus">Delete (or just check for) old messages.</div>';

$messages['deloldcfrm'] = 'This will permanently remove old emails from all folders according to the settings. Do you wish to continue?';
$messages['blurbcontent'] = 'You can set a global value that will apply to all folders that have no setting of their own (set to default). '.
			'See <i>Folders</i> settings to set values for specific folders.<br><br>Deletion of old messages can happen automatically at '.
			'either Login or Logout. Deletion at other times can be done with the icon on the mail menu bar.';
