<?php

$labels['buttontitle'] = 'Suppression automatique';
$labels['buttontext'] = 'Nettoyer';
$labels['numdeleted'] = ' courriels ont été supprimés avec succès.';
$labels['numchecked'] = ' courriels pourraient être supprimés.';

$labels['deloldmsgs'] = 'Politique de suppression';
$labels['deleteold'] = 'Supprimer après';
$labels['whenauto'] = 'Suppression automatique';
$labels['check'] = 'Chercher';
$labels['delete'] = 'Supprimer';
$labels['autonever'] = 'Jamais';
$labels['autologin'] = 'A la connexion';
$labels['autologout'] = 'A la déconnexion';
$labels['default'] = 'Par défaut';
$labels['never'] = '- jamais -';
$labels['1_week'] = '1 semaine';
$labels['2_week'] = '2 semaines';
$labels['1_month'] = '1 mois';
$labels['2_month'] = '2 mois';
$labels['6_month'] = '6 mois';
$labels['1_year'] = '1 an';
$labels['2_year'] = '2 ans';
$labels['3_year'] = '3 ans';
$labels['4_year'] = '4 ans';
$labels['5_year'] = '5 ans';
$labels['10_year'] = '10 ans';
$labels['15_year'] = '15 ans';

$messages['checking'] = 'Recherche des anciens courriels...';
$messages['deleting'] = 'Suppression des anciens courriels...';
$messages['dlgtxt'] = '<div id="dstus">Supprimer (ou juste vérifier) les anciens courriels.</div>';

$messages['deloldcfrm'] = 'Cela supprimera définitivement les anciens courriels de tous les dossiers en fonction des paramètres. Souhaitez-vous continuer ?';
$messages['blurbcontent'] = 'Vous pouvez définir une valeur globale qui s\'appliquera à tous les dossiers qui n\'ont pas leurs propres paramètres (définis par défaut). '.
    'Se rendre dans l\'onglet <i>Dossiers</i> pour définir des valeurs pour des dossiers spécifiques.<br /><br />La suppression d\'anciens messages peut se faire automatiquement à '.
                        'la connexion ou la déconnexion. La suppression à d\'autres moments peut être effectuée à l\'aide de l\'icône dans la barre de menu de la messagerie.';
